### ISSUE TITLE
Cometchat.UI does not install on new projects using monodroid81

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#7]
Good Morning,
I can not put the latest version of Xamarin.Android.CometChat.UI into a new project created by Visual Studio 2017.

I have already looked for this error elsewhere and in all cases they told me that it may be something with the distribution of the package that I am installing (in the case of cometchat.ui) in relation to the new Nuget.

Can you help me with this? 
Any new project I create can only use up to version 7.22.0

![2d7b96b5-9554-4eca-81a7-9a5f1d783525](https://user-images.githubusercontent.com/11754960/53975328-53d91400-40e3-11e9-9835-0694653733ed.png)

![1294d8b1-62e0-4395-8cf3-47b60ad70438](https://user-images.githubusercontent.com/11754960/53975341-5cc9e580-40e3-11e9-84ff-52fc2a68495e.png)

![b0a043b2-c045-43c3-8f56-af9e4370c4c3](https://user-images.githubusercontent.com/11754960/53975445-98fd4600-40e3-11e9-9e15-5abbf552685c.png)

**Comment by sushantinscripts** [comment]
Hello,

We are working on updating CometChatUI mono android. Once the testing finishes successfully, we'll update the Nuget package very soon and will let you know.

**Comment by sushantinscripts** [comment]
Hello,

We have made some changes related to monoandroid in our binding projects and have released a new nuget package 7.32.1. Kindly try this version and do let us know if this resolves the issue or not.

**Comment by joseBarreto** [comment]
Good afternoon,
Unfortunately I still have the same problem

![image](https://user-images.githubusercontent.com/11754960/54215554-e5bb9500-44c6-11e9-91a2-9234d1354f6d.png)

**Comment by sushantinscripts** [comment]
Hello,

Instead of updating, please try once by uninstalling both the packages and re-installing them.

**Comment by joseBarreto** [comment]
> Hello,
> 
> Instead of updating, please try once by uninstalling both the packages and re-installing them.


Still same problem, even uninstalling and installing again. =/


![image](https://user-images.githubusercontent.com/11754960/54280427-3b02af80-4576-11e9-8c1c-918bfc54f943.png)

**Comment by joseBarreto** [comment]
> Hello,
> 
> Instead of updating, please try once by uninstalling both the packages and re-installing them.

any idea what it might be?

**Comment by joseBarreto** [comment]
New version still does not install on newer Visual Studio 2017 projects.


![erroLagoinha](https://user-images.githubusercontent.com/11754960/54436484-5f46c380-4711-11e9-9c72-747e03018be7.png)

**Comment by joseBarreto** [comment]
**Any solution for this?** I need to publish my application to the store, and this error prevents because I can not get the latest version of the SDK.
My users are without the application only because of this.

**Comment by joseBarreto** [comment]
I've already tried to create a new project and put the SDK and it also does not work.
I need an alternative!

**Comment by lgurgel** [comment]
Hi guys,

We have a huge problem here. We have a deadline to deliver and we about to miss it because of this problem. Missing it will imply in heavy penalties we do not want to incur in. Please find a solution for this problem ASAP. It's a critical problem that need to be solved urgently.

**Comment by lgurgel** [comment]
Any solution? Any horizon for it?

**Comment by sushantinscripts** [comment]
Hi

We use visual studio 2017 and build both nuget packages using android 8.1. You have confirmed that this has been resolved on https://github.com/CometChat/xamarin-forms-chat-sdk-demo/issues/10. So please use that setup to build your apk.

**Comment by joseBarreto** [comment]
> Hi
> 
> We use visual studio 2017 and build both nuget packages using android 8.1. You have confirmed that this has been resolved on #10. So please use that setup to build your apk.

No, we did not confirm this in # 10.
Error # 10 was for older projects, which can install the SDK on new versions. The bug quoted there, and in reference to CometChat.Android version 7.33 which was closing the application.
This thread refers to projects created today that can not be used in the latest version of CometChat.

**Comment by joseBarreto** [comment]
> Hi
> 
> We use visual studio 2017 and build both nuget packages using android 8.1. You have confirmed that this has been resolved on #10. So please use that setup to build your apk.

Look, the test is simple. Just create a new solution, and try to add any version higher than 7.22 in the project. Does not install.
I installed my visual studio yesterday again, changed the machine, created a unique project of Xamarin.Android and still does not install.

**Comment by joseBarreto** [comment]
@sushantinscripts ?

**Comment by joseBarreto** [comment]
@sushantinscripts  ?

**Comment by mehtanishant** [comment]
Hi @joseBarreto,

We are currently working on the issue regarding monoandroid 8.1 version for the new projects. We will keep you posted about the progress.

**Comment by joseBarreto** [comment]
For those who have this problem, I have a tip.

You can download the CometChat package manually by clicking on the "Download package" button at https://www.nuget.org/packages/Xamarin.Android.CometChat.UI/

Once downloaded, change the extension from .nupkg to .zip.
Open the file, navigate to \ lib \ monoandroid, and extract the CometChatUIBinding.dll.

Remove the nuuget package xamarin.android.cometchat.ui in the android solution.
Then add the dll to the project.

This will free the app update on Google Play.

New projects created in visual studio 2019 apparently do not give this problem, but in old projects it still exists.

**Comment by joseBarreto** [comment]
Fix with VS2019 + CometChat 7.37
